# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAN_jPIJ-OV2ji5puKLIQY49urBmZbUK
"""

!pip install -q transformers torch

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

chat_history_ids = None

def chat_with_bot(user_input):
    global chat_history_ids
    new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors="pt")
    bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1) if chat_history_ids is not None else new_input_ids

    chat_history_ids = model.generate(
        bot_input_ids,
        max_length=1100,
        pad_token_id=tokenizer.eos_token_id,
        do_sample=True,
        top_k=80,
        top_p=0.95,
        temperature=0.7
    )

    bot_reply = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
    return bot_reply

while True:
    user_input = input("Você: ")
    if user_input.lower() in ["sair", "quit", "exit"]:
        print("Bot: Até logo!")
        break
    response = chat_with_bot(user_input)
    print(f"Bot: {response}")